name: forextradingapp
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  google_fonts: ^6.0.0
  cupertino_icons: ^1.0.2
  flutter_inappwebview: ^5.7.2+3
  youtube_player_flutter:
  intl:
  onesignal_flutter: ^3.5.0
  http:
  dio:
  rx_shared_preferences: ^3.0.0
  smooth_page_indicator:
  flutter_svg: ^2.0.7
  in_app_review: 

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/